DROP DATABASE IF EXISTS `tasks`;
CREATE DATABASE IF NOT EXISTS `tasks`;
USE `tasks`;

CREATE TABLE `tasks` (
	`list_id` INT(11) NOT NULL AUTO_INCREMENT,
	`task_id` INT(11) NOT NULL AUTO_INCREMENT,
	`person` VARCHAR(255) NOT NULL,
	`day` TINYINT(4) NOT NULL,
	`month` TINYINT(4) NOT NULL,
	`year` SMALLINT(6) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);